language: python
env:
- PYVER=2.7
- PYVER=3.6
- PYVER=3.7
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda${PYVER:0:1}-latest-Linux-x86_64.sh
  -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="/home/travis/miniconda/bin:$PATH"
- conda update --yes conda
- conda install --yes -c conda-forge -c alubbock python="$PYVER" numpy scipy nose
  pysb
- pip install python-dateutil
- pip install -r requirements.txt
install:
- pip install .
script:
- travis_wait 30 nosetests
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: ortega2247
  password:
    secure: aGKizWX93p2afLEWW9mGOlhxIOnJ3Aa4U0YViLzY3za/dzA8+IVBwam7YkL88MTlLJ6TaEAcOBTXJ5q24X3wpuZ43rWxO61ZucPqu63q9iHEAEVcPyUKgF4IFGSZyBcZaroSrMtX1sKWNNQB3ZQZy+FilANld5G/aW3CtRl3AAMyMl/BtgJqtEfpFj5jcglB/BZSs+i/+UPgCk0lxrr2MEFO7blWele4XQDubFy0UWegjwlDd90oMvJ6qcF1rZoaNeGR1R1kSnTZpEcS+EsZ8azthytsRqOXiThUylAJhhVKKa5L8HFiuowaI/TShVzEwC6we8BYOMkgwimQW7F4Kn3IeUZM+yXSt2Lmega021v77ygT+7lZBdo6wL6l4g7ihHczqjKJ7xlwFGLPi+wsl/iegUU++ylpDqjzf30uLr3vBSYiYuxTt+DW9PDPb1c/6rXvgwqCfoIbQe60xuz6H1yq5qQnGUrrQe3f44ZpktKSfVzHUWHvTOti/S/HGf+VVVpKNph76SwTyVm4C0tbc5Tg6xtrdmcwz+7Nn08dE2N3aCq+WGwBQWtb4ODsWgbWt5qQoSJY2d2gUVhNZkxe17eKI9jOKCJ5TNUCDkhPy4EBo8Xpg0l+5pSmIQO/8H3FdbqWtM2lbqjYlhEZY/LrMDrpe0Y4wVrrdujIWK9sJUU=
  on:
    branch: master
    tags: true
    condition: $PYVER = 2.7
